title: # a name for your Learning Lab course
tagline: # a short description for your Learning Lab course, displayed on the course catalog
description: # a longer description for your Learning Lab course, displayed on the course's landing page

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name:     java-test
  repo:     penny-appleton/java-test

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: # the type of action, full list at https://lab.github.com/docs/actions/
  # some actions require additional options, those should appear below `type:`
  # you can execute multiple actions in the `before` block

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
Step 1: The TDD cycle 
- title: Scenario 1 - ISBN Validator
  description: you will write an ISBN Validator using TDD
  event: push
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

 Step 2: Using Mocks 
 - title: Scenario 2 - Book Locator Code Generator 
  description: you will implement a book locator code generator using TDD and Mocks
  event: push
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

 Step 3: Refactoring
 - title: Scenario 3 - Refactoring
  description: you will use what you have learned in scenarios 1 and 2 to help you refactor the code
  event: push
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions


